name: flutter_easyrefresh
description: A widget provided to the flutter scroll component drop-down refresh and pull up load.
version: 2.0.4
author: xuelongqy <xuelongqy@foxmail.com>
homepage: https://github.com/vickyleu/flutter_easyrefresh

environment:
  sdk: ">=2.5.0 <3.0.0"
#  flutter: ">=1.9.1+hotfix.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
